### ISSUE TITLE
[NOT AN ISSUE] : Installation steps?

### ISSUE THREAD

**Issue by IIPoliII** [BluePsyduck/factorio-mod-portal-client#1]
I don't exactly understand how do you install this mod portal?  Is it possible to download mods via it ? And update the mods ?

Nice to see this out in php C: ! Great job

**Comment by BluePsyduck** [comment]
This library is intended to be installed through Composer (package name "bluepsyduck/factorio-mod-portal-client") and is prepared to be used in a Zend Expressive project. If not used in a Zend Expressive context, it is necessary to write additional code to get the client running.

The client is only accessing the API of the Mod portal as documented here: https://wiki.factorio.com/Mod_portal_API
This API is limited to reading access, so downloading mods is possible (the reason why I wrote this client :D), updating them on the mod portal is not.
